In [4]:
#from google.colab import drive
#drive.mount('/content/gdrive')
rootpath = 'Patches_diaretdb1/'

In [5]:
import matplotlib.pyplot as plt
import cv2
import glob
import numpy as np

In [6]:
#Create numpy array of images
X = []
files = glob.glob (rootpath+"*.png")
#print(files)
files.sort()
# files = sorted(files)
for myFile in files:
    #print(myFile)
    image = cv2.imread (myFile,0)
    X.append (image)

X = np.array(X)
print('X_data shape:', X.shape)
print(len(X))

X_data shape: (0,)
0


In [7]:
y = ['No','No','Yes','No','Yes','No','No','Yes','Yes','No','No','No','No','Yes','No',
     'No','No','Yes','No','Yes','Yes','No','Yes','Yes','No','No','Yes','Yes','Yes','Yes',
     'No','Yes','Yes','No','Yes','No','No','Yes','Yes','No','No','Yes','Yes','Yes','Yes',
     'No','Yes','Yes','Yes','Yes','No','No','Yes','Yes','No','Yes','Yes','No','Yes','No',
     'Yes','No','Yes','No','Yes','Yes','No','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes',
     'Yes','No','No','No','Yes','No','No','Yes','Yes','No','No','No','No','Yes','No',
     'Yes','Yes','Yes','No','Yes','No','No','No','Yes','No','Yes','Yes','Yes','Yes','No',
     'Yes','No','Yes','Yes','Yes','Yes','No','Yes','Yes','No','Yes','Yes','Yes','Yes','Yes',
     'No','No','Yes','No','Yes','Yes','No','No','Yes','No','No','No','No','Yes','Yes',
     'No','No','Yes','No','Yes','Yes','No','No','Yes','No','Yes','Yes','Yes','Yes','Yes',
     'No','No','Yes','No','Yes','Yes','No','Yes','Yes','No','Yes','Yes','Yes','Yes','Yes',
     'No','No','No','No','Yes','No','No','Yes','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','Yes','Yes','No','Yes','No','Yes','Yes','Yes',
     'Yes','No','No','No','No','Yes','No','No','No','No','Yes','Yes','Yes','Yes','No',
     'Yes','No','Yes','Yes','Yes','Yes','Yes','Yes','Yes','No','Yes','Yes','Yes','Yes','Yes',
     'Yes','Yes','Yes','No','Yes','Yes','No','No','No','No','Yes','Yes','Yes','No','Yes',
     'Yes','No','No','No','Yes','No','No','Yes','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','Yes','Yes','No','No','Yes','No','Yes','Yes',
     'No','Yes','Yes','Yes','No','Yes','Yes','Yes','Yes','No','No','Yes','Yes','Yes','Yes',
     'No','Yes','Yes','Yes','Yes','Yes','No','Yes','Yes','No','Yes','Yes','Yes','Yes','Yes',
     'No','Yes','Yes','Yes','Yes','Yes','No','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes',
     'Yes','No','Yes','Yes','No','Yes','No','Yes','Yes','No','No','No','No','Yes','Yes',
     'No','No','No','No','No','Yes','No','No','No','No','Yes','Yes','No','No','Yes',
     'No','No','No','No','No','Yes','No','No','No','No','Yes','Yes','Yes','No','Yes',
     'No','No','Yes','No','Yes','Yes','No','No','No','No','Yes','Yes','Yes','No','Yes',
     'No','Yes','Yes','No','No','No','No','No','Yes','Yes','Yes','Yes','Yes','Yes','Yes',
     'Yes','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','No','Yes','Yes','No',
     'No','No','No','Yes','Yes','No','Yes','No','Yes','No','No','No','No','Yes','No',
     'No','Yes','No','No','Yes','No','Yes','No','No','Yes','Yes','Yes','Yes','Yes','No',
     'No','No','No','No','Yes','No','No','Yes','Yes','No','No','No','No','Yes','No', #30
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','No','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','Yes','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','Yes','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No', 
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','Yes','No','Yes','No','No','Yes','No','Yes','No',
     'No','No','No','No','Yes','No','Yes','No','Yes','No','Yes','Yes','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','Yes','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','Yes', #50
     'No','No','No','No','Yes','No','No','Yes','Yes','No','No','No','No','Yes','Yes',
     'No','No','Yes','Yes','Yes','No','No','No','Yes','No','Yes','No','Yes','Yes','No',
     'No','No','Yes','Yes','Yes','Yes','Yes','No','Yes','No','No','Yes','No','Yes','Yes',
     'No','No','No','No','Yes','No','No','No','Yes','No','Yes','Yes','No','Yes','No',
     'No','No','Yes','No','Yes','No','No','Yes','Yes','No','No','No','No','Yes','Yes',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','Yes',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','Yes','No','No','Yes','No','No','Yes','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','Yes','Yes','No','No','No','No','Yes','No', #60
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','Yes','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','Yes','No','Yes','No','Yes','Yes','Yes','No','Yes','No','No','Yes','No',
     'No','No','No','No','Yes','No','Yes','No','No','No','Yes','Yes','No','Yes','Yes',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','Yes','Yes','Yes','No','No','Yes','No','No','No','No','Yes','Yes',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','Yes','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No', #70
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','Yes','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','Yes','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','Yes','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','Yes','Yes','No','No','No','No','Yes','No', #79
     'Yes','Yes','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','Yes','No','No','Yes','No','No','No','Yes','No','No','No','Yes','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','Yes','No','Yes','No',
     'No','No','No','No','No','Yes','No','No','No','No','Yes','Yes','No','No','Yes',
     'No','No','No','No','No','Yes','No','No','No','No','No','Yes','No','No','Yes',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','No','No','Yes','No',
     'No','No','No','No','Yes','No','No','No','Yes','No','No','Yes','No','Yes','No' #89
     ]

In [0]:
y = np.asarray(y) 
print(y.shape)

(1335,)


In [0]:
img_index = 25
#plt.imshow(X_data1[:,:,:,img_index])
#plt.show()
print(y[img_index])

No


In [0]:
print(len(X))
print(len(y))

1335
1335


In [0]:
from sklearn.utils import shuffle
# X = X.reshape(X.shape[0],X.shape[1]*X.shape[2]).T
# y = y.reshape(y.shape[0],)
X = np.reshape(X, [X.shape[0], X.shape[1]*X.shape[2]])

X, y = shuffle(X, y, random_state=42)

In [0]:
#############################   Random Forest Algorithm  ##############################

In [0]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=25)
print(clf)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=25,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=25,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
from sklearn.metrics import accuracy_score

preds = clf.predict(X_test)
print("Accuracy:", accuracy_score(y_test,preds))

Accuracy: 0.7005347593582888


In [0]:
#print(preds)
pred_prob = clf.predict_proba(X_test)
#print(pred_prob)

In [0]:
from sklearn.metrics import precision_recall_fscore_support

In [0]:
precision_recall_fscore_support(y_test, preds, average=None)

(array([0.72230014, 0.63063063]),
 array([0.86264657, 0.41420118]),
 array([0.78625954, 0.5       ]),
 array([597, 338]))

In [0]:
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score
print(f1_score(y_test, preds, average=None))

[0.78625954 0.5       ]


In [0]:
for i in range(len(y_test)):
    if(y_test[i]=='No'):
        #print(y_test[i])
        num = int(0)
        #print(type(num))
        y_test[i]= int(num)
        #print(type(y_test[i]))
        #print(y_test[i])
    else:
        num = int(1)
        y_test[i]=int(num)
        #print(type(y_test[i]))
        
    if(preds[i]=='No'):
        num = int(0)
        preds[i]=int(num)
    else:
        num = int(1)
        preds[i]=int(num)

#print(y_test)
#print(preds)

In [0]:
y_test = list(map(int, y_test)) 
preds = list(map(int, preds)) 

In [0]:
print(roc_auc_score(y_test, preds))

0.6384238747980534


In [0]:
from sklearn.metrics import roc_curve, auc, roc_auc_score
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, pred_prob)

In [0]:
print(auc(false_positive_rate, true_positive_rate))

0.6384238747980534


In [0]:
###############################  Neural Network Algorithm-40 Neurons ##############################

In [0]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y, test_size = 0.7)

In [0]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes= 40)
mlp.fit(X_train1, y_train1)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=40, learning_rate='constant',
              learning_rate_init=0.001, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [0]:
preds1 = mlp.predict(X_test1)
#print(preds1)

#preds = clf.predict(X_test)
print("Accuracy:", accuracy_score(y_test1,preds1))

Accuracy: 0.35508021390374334


In [0]:
#print(preds)
pred_prob = mlp.predict_proba(X_test1)
#print(pred_prob)

In [0]:
precision_recall_fscore_support(y_test1, preds1, average=None)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([0.        , 0.35508021]),
 array([0., 1.]),
 array([0.        , 0.52407261]),
 array([603, 332]))

In [0]:
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score
print(f1_score(y_test1, preds1, average=None))

[0.         0.52407261]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [0]:
for i in range(len(y_test1)):
    if(y_test1[i]=='No'):
        #print(y_test[i])
        num = int(0)
        #print(type(num))
        y_test1[i]= int(num)
        #print(type(y_test[i]))
        #print(y_test[i])
    else:
        num = int(1)
        y_test1[i]=int(num)
        #print(type(y_test[i]))
        
    if(preds1[i]=='No'):
        num = int(0)
        preds1[i]=int(num)
    else:
        num = int(1)
        preds1[i]=int(num)

#print(y_test)
#print(preds)

In [0]:
y_test1 = list(map(int, y_test1)) 
preds1 = list(map(int, preds1)) 

In [0]:
print(roc_auc_score(y_test1, preds1))

0.5


In [0]:
################################## Support Vector Machine Algorithm ####################################

In [0]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, test_size = 0.7)

In [0]:
from sklearn import svm
svl = svm.SVC()

In [0]:
svl.fit(X_train2,y_train2)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [0]:
preds2 = svl.predict(X_test2)
#print(preds2)

print("Accuracy:", accuracy_score(y_test2,preds2))

Accuracy: 0.6363636363636364


In [0]:
##print(preds)
#pred_prob = svl.predict_proba(X_test2)
#print(pred_prob)

In [0]:
precision_recall_fscore_support(y_test2, preds2, average=None)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([0.63636364, 0.        ]),
 array([1., 0.]),
 array([0.77777778, 0.        ]),
 array([595, 340]))

In [0]:
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score
print(f1_score(y_test2, preds2, average=None))

[0.77777778 0.        ]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [0]:
for i in range(len(y_test2)):
    if(y_test2[i]=='No'):
        #print(y_test[i])
        num = int(0)
        #print(type(num))
        y_test2[i]= int(num)
        #print(type(y_test[i]))
        #print(y_test[i])
    else:
        num = int(1)
        y_test2[i]=int(num)
        #print(type(y_test[i]))
        
    if(preds2[i]=='No'):
        num = int(0)
        preds2[i]=int(num)
    else:
        num = int(1)
        preds2[i]=int(num)

#print(y_test)
#print(preds)

In [0]:
y_test2 = list(map(int, y_test2)) 
preds2 = list(map(int, preds2)) 

In [0]:
print(roc_auc_score(y_test2, preds2))

0.5


In [0]:
###############################  Neural Network Algorithm-100 Neurons ##############################

In [0]:
X_train3, X_test3, y_train3, y_test3 = train_test_split(X, y, test_size = 0.7)

In [0]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes= 100)
mlp.fit(X_train3, y_train3)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=100, learning_rate='constant',
              learning_rate_init=0.001, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [0]:
preds3 = mlp.predict(X_test3)
#print(preds1)

#preds = clf.predict(X_test)
print("Accuracy:", accuracy_score(y_test3,preds3))

Accuracy: 0.6438502673796791


In [0]:
precision_recall_fscore_support(y_test3, preds3, average=None)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([0.64385027, 0.        ]),
 array([1., 0.]),
 array([0.78334418, 0.        ]),
 array([602, 333]))

In [0]:
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score
print(f1_score(y_test3, preds3, average=None))

[0.78334418 0.        ]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [0]:
for i in range(len(y_test3)):
    if(y_test3[i]=='No'):
        #print(y_test[i])
        num = int(0)
        #print(type(num))
        y_test3[i]= int(num)
        #print(type(y_test[i]))
        #print(y_test[i])
    else:
        num = int(1)
        y_test3[i]=int(num)
        #print(type(y_test[i]))
        
    if(preds3[i]=='No'):
        num = int(0)
        preds3[i]=int(num)
    else:
        num = int(1)
        preds3[i]=int(num)

#print(y_test)
#print(preds)

In [0]:
y_test3 = list(map(int, y_test3)) 
preds3 = list(map(int, preds3)) 

In [0]:
print(roc_auc_score(y_test3, preds3))

0.5
